version: '2.0'
services:
  trisads:
    build: "."
    image: "trisa/trisads:latest"
    ports:
      - 4433:4433
    volumes:
      - ./fixtures/db:/data
  envoy:
    build: "./proxy"
    image: "trisa/grpc-proxy:latest"
    ports:
      - 8080:8080
  dsui:
    build: "./web"
    image: "trisa/dsweb:latest"
    ports:
      - 8000:80
