// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RegisterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

type RegisterReply struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReply) Reset()         { *m = RegisterReply{} }
func (m *RegisterReply) String() string { return proto.CompactTextString(m) }
func (*RegisterReply) ProtoMessage()    {}
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *RegisterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReply.Unmarshal(m, b)
}
func (m *RegisterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReply.Marshal(b, m, deterministic)
}
func (m *RegisterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReply.Merge(m, src)
}
func (m *RegisterReply) XXX_Size() int {
	return xxx_messageInfo_RegisterReply.Size(m)
}
func (m *RegisterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReply.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReply proto.InternalMessageInfo

func (m *RegisterReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LookupRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupRequest) Reset()         { *m = LookupRequest{} }
func (m *LookupRequest) String() string { return proto.CompactTextString(m) }
func (*LookupRequest) ProtoMessage()    {}
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *LookupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupRequest.Unmarshal(m, b)
}
func (m *LookupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupRequest.Marshal(b, m, deterministic)
}
func (m *LookupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupRequest.Merge(m, src)
}
func (m *LookupRequest) XXX_Size() int {
	return xxx_messageInfo_LookupRequest.Size(m)
}
func (m *LookupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LookupRequest proto.InternalMessageInfo

func (m *LookupRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LookupReply struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Vasp                 *VASP    `protobuf:"bytes,2,opt,name=vasp,proto3" json:"vasp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LookupReply) Reset()         { *m = LookupReply{} }
func (m *LookupReply) String() string { return proto.CompactTextString(m) }
func (*LookupReply) ProtoMessage()    {}
func (*LookupReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *LookupReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LookupReply.Unmarshal(m, b)
}
func (m *LookupReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LookupReply.Marshal(b, m, deterministic)
}
func (m *LookupReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LookupReply.Merge(m, src)
}
func (m *LookupReply) XXX_Size() int {
	return xxx_messageInfo_LookupReply.Size(m)
}
func (m *LookupReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LookupReply.DiscardUnknown(m)
}

var xxx_messageInfo_LookupReply proto.InternalMessageInfo

func (m *LookupReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *LookupReply) GetVasp() *VASP {
	if m != nil {
		return m.Vasp
	}
	return nil
}

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type SearchReply struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Vasps                []*VASP  `protobuf:"bytes,2,rep,name=vasps,proto3" json:"vasps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchReply) Reset()         { *m = SearchReply{} }
func (m *SearchReply) String() string { return proto.CompactTextString(m) }
func (*SearchReply) ProtoMessage()    {}
func (*SearchReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *SearchReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchReply.Unmarshal(m, b)
}
func (m *SearchReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchReply.Marshal(b, m, deterministic)
}
func (m *SearchReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchReply.Merge(m, src)
}
func (m *SearchReply) XXX_Size() int {
	return xxx_messageInfo_SearchReply.Size(m)
}
func (m *SearchReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchReply.DiscardUnknown(m)
}

var xxx_messageInfo_SearchReply proto.InternalMessageInfo

func (m *SearchReply) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *SearchReply) GetVasps() []*VASP {
	if m != nil {
		return m.Vasps
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "pb.Error")
	proto.RegisterType((*RegisterRequest)(nil), "pb.RegisterRequest")
	proto.RegisterType((*RegisterReply)(nil), "pb.RegisterReply")
	proto.RegisterType((*LookupRequest)(nil), "pb.LookupRequest")
	proto.RegisterType((*LookupReply)(nil), "pb.LookupReply")
	proto.RegisterType((*SearchRequest)(nil), "pb.SearchRequest")
	proto.RegisterType((*SearchReply)(nil), "pb.SearchReply")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0xd8, 0xd4, 0x66, 0x62, 0x5a, 0xba, 0x7a, 0x08, 0x45, 0x6c, 0x59, 0x10, 0x7a,
	0x0a, 0x12, 0xf5, 0x03, 0x14, 0xf4, 0x20, 0x14, 0x91, 0x8d, 0x78, 0xcf, 0x9f, 0xa1, 0x06, 0x53,
	0x76, 0xbb, 0x9b, 0x08, 0xf9, 0x42, 0x7e, 0x4e, 0xc9, 0xae, 0xd1, 0xc6, 0x53, 0x6f, 0x99, 0x37,
	0x3f, 0xde, 0xcb, 0x3c, 0x16, 0xdc, 0x44, 0x14, 0xa1, 0x90, 0xbc, 0xe2, 0xc4, 0x16, 0xe9, 0xfc,
	0x6c, 0xc7, 0x73, 0x2c, 0x95, 0x51, 0xe8, 0x3d, 0x38, 0x8f, 0x52, 0x72, 0x49, 0x08, 0x0c, 0x33,
	0x9e, 0x63, 0x60, 0x2d, 0xad, 0x95, 0xc3, 0xf4, 0x37, 0x09, 0xe0, 0x74, 0x87, 0x4a, 0x25, 0x5b,
	0x0c, 0xec, 0xa5, 0xb5, 0x72, 0x59, 0x37, 0xd2, 0x19, 0x4c, 0x19, 0x6e, 0x0b, 0x55, 0xa1, 0x64,
	0xb8, 0xaf, 0x51, 0x55, 0xf4, 0x06, 0xfc, 0x3f, 0x49, 0x94, 0x0d, 0x59, 0x80, 0x83, 0xad, 0xb5,
	0xb6, 0xf4, 0x22, 0x37, 0x14, 0x69, 0xa8, 0xb3, 0x98, 0xd1, 0xe9, 0x02, 0xfc, 0x0d, 0xe7, 0x1f,
	0xb5, 0xf8, 0xb1, 0x20, 0x13, 0xb0, 0x8b, 0x5c, 0xe3, 0x3e, 0xb3, 0x8b, 0x9c, 0x6e, 0xc0, 0xeb,
	0x80, 0x63, 0x0c, 0xc9, 0x25, 0x0c, 0x3f, 0x13, 0x25, 0xf4, 0xcf, 0x7a, 0xd1, 0xb8, 0xdd, 0xbf,
	0xad, 0xe3, 0x17, 0xa6, 0x55, 0x7a, 0x0d, 0x7e, 0x8c, 0x89, 0xcc, 0xde, 0xbb, 0xb8, 0x0b, 0x70,
	0xf6, 0x35, 0xca, 0x46, 0xfb, 0xb9, 0xcc, 0x0c, 0xf4, 0x19, 0xbc, 0x0e, 0x3b, 0x2a, 0xf4, 0x0a,
	0x9c, 0xd6, 0x5e, 0x05, 0xf6, 0xf2, 0xa4, 0x97, 0x6a, 0xe4, 0xe8, 0xcb, 0x82, 0xc9, 0x2b, 0x7b,
	0x8a, 0xd7, 0x0f, 0x85, 0xc4, 0xac, 0xe2, 0xb2, 0x21, 0x77, 0x30, 0xee, 0xaa, 0x22, 0xe7, 0x2d,
	0xff, 0xaf, 0xcb, 0xf9, 0xac, 0x2f, 0x8a, 0xb2, 0xa1, 0x03, 0x12, 0xc2, 0xc8, 0xb4, 0x41, 0xf4,
	0xba, 0x57, 0xdd, 0x7c, 0x7a, 0x28, 0xfd, 0xf2, 0xe6, 0x10, 0xc3, 0xf7, 0x6e, 0x37, 0xfc, 0xc1,
	0x9d, 0x74, 0x90, 0x8e, 0xf4, 0x8b, 0xb8, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x78, 0xaf, 0x3d,
	0x04, 0x30, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TRISADirectoryClient is the client API for TRISADirectory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TRISADirectoryClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error)
	Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupReply, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error)
}

type tRISADirectoryClient struct {
	cc *grpc.ClientConn
}

func NewTRISADirectoryClient(cc *grpc.ClientConn) TRISADirectoryClient {
	return &tRISADirectoryClient{cc}
}

func (c *tRISADirectoryClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterReply, error) {
	out := new(RegisterReply)
	err := c.cc.Invoke(ctx, "/pb.TRISADirectory/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tRISADirectoryClient) Lookup(ctx context.Context, in *LookupRequest, opts ...grpc.CallOption) (*LookupReply, error) {
	out := new(LookupReply)
	err := c.cc.Invoke(ctx, "/pb.TRISADirectory/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tRISADirectoryClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error) {
	out := new(SearchReply)
	err := c.cc.Invoke(ctx, "/pb.TRISADirectory/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TRISADirectoryServer is the server API for TRISADirectory service.
type TRISADirectoryServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterReply, error)
	Lookup(context.Context, *LookupRequest) (*LookupReply, error)
	Search(context.Context, *SearchRequest) (*SearchReply, error)
}

func RegisterTRISADirectoryServer(s *grpc.Server, srv TRISADirectoryServer) {
	s.RegisterService(&_TRISADirectory_serviceDesc, srv)
}

func _TRISADirectory_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TRISADirectoryServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TRISADirectory/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TRISADirectoryServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TRISADirectory_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TRISADirectoryServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TRISADirectory/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TRISADirectoryServer).Lookup(ctx, req.(*LookupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TRISADirectory_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TRISADirectoryServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.TRISADirectory/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TRISADirectoryServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TRISADirectory_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.TRISADirectory",
	HandlerType: (*TRISADirectoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _TRISADirectory_Register_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _TRISADirectory_Lookup_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _TRISADirectory_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
